version: "3"

services:
  app:
    container_name: ${APP_NAME}_app
    build: .
    volumes:
      - ./${APP_NAME}:/app
    ports:
      - "8080:8080"
      
  postgres:
    container_name: ${APP_NAME}_db
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_DB: ${APP_NAME}_development
      POSTGRES_PASSWORD: password
    volumes:
      - /home/postgres:/var/lib/postgresql/data
      - ./docker-compose/db_restore:/home/db_restore
    ports:
      - "5433:5432"