services:
  app:
    container_name: ${APP_NAME}_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
    volumes:
      - ./app:/app
      - ./docker-compose/m2-repo:/root/.m2/repository  # Volume para persistir o repositório Maven
    ports:
      - "8080:8080"
      - "9222:9222"

  postgres:
    container_name: ${APP_NAME}_db
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_DB: ${APP_NAME}_development
      POSTGRES_PASSWORD: password
    volumes:
      - /home/postgres/${APP_NAME}:/var/lib/postgresql/data
      - ./docker-compose/db_restore:/home/db_restore
    ports:
      - "5433:5432"